export { default as Header } from './Header';
export { default as Title } from './Title';
export { default as Categories } from './Categories';
export { default as Button } from './Button';
export { default as Food } from './Food';
export { default as FoodItem } from './FoodItem';
export { default as CartFood } from './CartFood';
export { default as Home } from './Home';
export { default as SearchFood } from './SearchFood';
